### ISSUE TITLE
jmp/call byte address annotation in comment

### ISSUE THREAD

**Issue by petesoper** [vsergeev/vavrdisasm#3]
This is a wonderful, easy to use tool. THANKS for making this.
But I tripped over the word addresses in jmp and call instructions immediately.
Why this:
  7c8a:	3e 80 94 0e	call	0x3e80

Instead of this:
7c8a:	3e 80 94 0e	call	0x3e80  ; 0x7d00

??
I've blown the dust off my hex calculator and I'm getting along fine with your tool, but it would be more convenient if word addresses were translated to byte addresses in the comments for jmp and call (and others like it) as you're already doing for branch instructions.
Best Regards,
Pete

**Comment by dsalychev** [comment]
Hi, Pete.

I just wonder why you aren't using `avr-objdump`? Something like `avr-objdump -m avr -D ./dhtc.hex` to disassemble a hex file.

**Comment by petesoper** [comment]
Hi Dimitry,

    Good point. I've been using avr-objdump heavily, but for ELF files, 
not noticing hex files are supported if the architecture is spelled out. 
Thanks for that!

   But your program makes it easy to form pipes that allow me to confirm 
some hex file edits I'm doing are correct, and by virtue of the 
available source code I could add some specific labeling features of 
interest to my situation. I'm slicing up image files as part of an 
experiment to implement a kind of "overlay" system where a "shell" loads 
application programs into an AVR chip along side itself and (with luck 
and a tail wind)  the apps share use of a set of libraries. This is part 
of an educational project I'm doing with an exceptionally bright student 
in my area. The latter, "library sharing" feature requires us to edit 
the library part of an application's image out of the hex file. I wanted 
a disassembler that could be spliced into the tool chain and customized 
your program fits the bill.

   Thanks again for making this available to the community. I hope you 
and your family and friends are well and happy during this holiday season.

Pete

**Comment by dsalychev** [comment]
Pete,

ah, I understand, but I'm probably not a person who you addressed your words to. I didn't create this disassembler, but @vsergeev. I just included one of Vanya's project, libGIS, into my simulator for microcontrollers to be able to read Intel HEX. It's really nice to see that there is an interest in AVRs somewhere beyond Arduino, to be honest.

Let me ask you about this shell of yours. Why do you want to have some kind of envelop over actual program in AVR? Do you want to be able to manage the last one somehow? Be able to access AVR's internal state like I/O registers?

I'd like to wish you and your family all the best, too.
Merry Christmas and Happy New Year.

**Comment by vsergeev** [comment]
@petesoper 

I totally agree that having byte addresses in the comment would help debugging. If I remember correctly, the original motivation for showing word addresses was to generate assembly that was compatible with AVR Assembler. I believe jump/call instructions in AVR Assembler expect word addresses, when given a numeric operand rather than a label.
